// Renders every sprite of a theme to PNG, plus a gallery page, for reviewing and discussing them one by one
// (docs/sprites/README.md, docs/superpowers/specs/2026-10-06-sprite-themes-design.md). No dependencies.
//   node tools/sprite_sheet.mjs [--theme tier2] [--scale 4] [--out docs/sprites]
// Re-run after editing a map or a palette: the PNGs are committed so issues and the gallery can show them.
// To browse every theme live instead, see tools/sprites.html.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { RES } from '../ui/sprites.js';
import { THEMES, T, setTheme } from '../ui/theme.js';
import '../ui/themes.js';
import { catalog } from './sprite_catalog.mjs';
import { png, rgba } from './png_write.mjs';

const arg = (name, dflt) => { const i = process.argv.indexOf(`--${name}`); return i > 0 ? process.argv[i + 1] : dflt; };
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const themeId = arg('theme', 'tier2'), scale = Number(arg('scale', 4)), outRoot = path.resolve(root, arg('out', 'docs/sprites'));
if (!THEMES[themeId]) throw new Error(`unknown theme ${themeId}: ${Object.keys(THEMES).join(', ')}`);
setTheme(themeId); // the theme's palette and its own art (sprites.js), where it has some

// Cells side by side, 2 art px apart, each scaled; a map char resolves through the theme's px and the cell's overrides.
function strip(cells) {
  const gap = 2, fw = cells.map(c => Math.max(...c.rows.map(r => r.length))), fh = Math.max(...cells.map(c => c.rows.length));
  const w = fw.reduce((a, b) => a + b, 0) + gap * (cells.length - 1), px = new Array(w * fh).fill(null);
  let x0 = 0;
  cells.forEach(({ rows, over }, i) => {
    const pal = { ...T.px, ...over };
    rows.forEach((row, y) => { for (let x = 0; x < row.length; x++) if (row[x] !== '.') px[y * w + x0 + x] = pal[row[x]]; });
    x0 += fw[i] + gap;
  });
  return { h: fh * scale, buf: png(w * scale, fh * scale, (x, y) => rgba(px[Math.floor(y / scale) * w + Math.floor(x / scale)])) };
}

// Where each map is drawn: the ui files that name it.
const uiDir = path.join(root, 'ui'), sources = fs.readdirSync(uiDir).filter(f => f.endsWith('.js') && f !== 'sprites.js');
const usedIn = name => sources.filter(f => new RegExp(`MAPS\\.${name}\\b|'${name}'`).test(fs.readFileSync(path.join(uiDir, f), 'utf8')));

const outDir = path.join(outRoot, themeId);
fs.mkdirSync(outDir, { recursive: true });
const entries = catalog().map(e => {
  const { h, buf } = strip(e.cells), file = `${e.id}.png`;
  fs.writeFileSync(path.join(outDir, file), buf);
  let note = `${e.note}. Source: \`ui/art/${e.src}.png\``;
  if (e.group === 'Props and furniture' && !e.id.includes('.')) { const where = usedIn(e.id); note += `, drawn by ${where.length ? where.join(', ') : '(not referenced by name)'}`; }
  return { ...e, file, h, note };
});

// Gallery page: one row per sprite, an anchor per sprite to link from its discussion issue.
const groups = [...new Set(entries.map(e => e.group))];
const md = [`# Sprites — ${T.name}`, '',
  `Generated by \`node tools/sprite_sheet.mjs --theme ${themeId}\` from the art files in \`ui/art/\` and the palette in \`ui/theme.js\`. Do not edit by hand.`,
  `Each image is ${scale}× the art pixels (the art is ${RES}× the logical scene pixels). Sizes are logical px.`, '',
  'To browse every theme side by side, animated and zoomable, open the live viewer `tools/sprites.html` (see its header).',
  'To discuss a sprite, open a **Sprite** issue (New issue → Sprite) and paste the sprite id; see',
  '[the design note](../superpowers/specs/2026-10-06-sprite-themes-design.md#discussing-sprites).', ''];
for (const grp of groups) {
  md.push(`## ${grp}`, '', '| Sprite | Logical size | Notes | Image |', '|---|---|---|---|');
  for (const e of entries.filter(x => x.group === grp)) md.push(`| <a id="${e.id.toLowerCase().replace(/\./g, '-')}"></a>\`${e.id}\` | ${e.size} | ${e.note} | <img src="${themeId}/${e.file}" height="${Math.min(e.h, 160)}"> |`);
  md.push('');
}
fs.writeFileSync(path.join(outRoot, themeId === 'tier2' ? 'README.md' : `${themeId}.md`), md.join('\n'));
console.log(`${entries.length} sprites -> ${path.relative(root, outDir)}`);
