// Tier II palette and pixel maps (ported from the Claude Design board "Tier II — Data-Shrine").
export const BASE = {
  k: '#0e0a08', g: '#b8742e', G: '#6e3f17', p: '#d6c79f', P: '#a8946a', w: '#4a3020', W: '#2e1c12',
  m: '#5a5e63', M: '#2a2c30', c: '#7cff9e', C: '#16301f', f: '#f0a83c', F: '#ffe6a0', x: '#8e1c16',
  b: '#cfc3a8', B: '#948669', n: '#140c08', u: '#2b3f5e', v: '#2f4a33', r: '#5e1710', d: '#3a0d09',
  a: '#ff3a20', o: '#7cff9e', y: '#d9a84e', s: '#b89a7c', e: '#120c0a',
  // HD mid-tones/highlights: robe lit, brass lit, iron lit, optic glint, wood lit
  R: '#8c2c1c', h: '#e8b45a', l: '#8a9096', O: '#e6ffee', L: '#6a4630',
  // adept robe: bone mid, bone shadow
  q: '#a89a78', Q: '#6a5e48',
  // rank markers in the scribe maps (t hood rim, T shoulder seam, z cog, j cog hub): robe-coloured unless RANK gilds them
  t: '#8c2c1c', T: '#3a0d09', z: '#5e1710', j: '#5e1710',
  J: '#a89a78', I: '#a89a78', // adept hood cog, bone unless gilded
};
export const SASH = ['#d9a84e', '#5fae7a', '#5a7ec9', '#c46a9a', '#c9b95a', '#6ac9c4', '#c97a4a', '#9a8ad9'];

// Rank by model: opus/fable high, haiku novice, anything else (sonnet, unknown) standard. Edit here.
export const rankOf = model => (/opus|fable/i.test(model ?? '') ? 'high' : /haiku/i.test(model ?? '') ? 'novice' : 'standard');
// robe: scribe palette overrides; adept: adept palette overrides (x = hem/stripe trim).
const gilt = (r, R, d) => ({ r, R, d, z: '#e8b45a', j: '#6e3f17', t: '#e8b45a', T: '#b8742e', g: '#e8b45a', G: '#b8742e' });
const plain = (r, R, d) => ({ r, R, d, z: r, j: r, t: R, T: d, g: d, G: d });
export const RANK = {
  high: { name: 'Magos', robe: gilt('#6e120d', '#9a2a18', '#300806'), adept: { x: '#d9a84e', b: '#e8dcb8', J: '#e8b45a', I: '#6e3f17' } },
  standard: { name: 'Tech-priest', robe: {}, adept: {} },
  novice: { name: 'Novice', robe: plain('#6e3a30', '#8a5244', '#43231c'), adept: { x: '#5a564c', q: '#8e8a7e', Q: '#5a564c', b: '#a8a496', J: '#8e8a7e', I: '#8e8a7e' } },
};

export const RES = 2; // art pixels per logical pixel
// Nearest-neighbour 2x upscale of a hand-written map: each char doubles horizontally, each row doubles vertically.
// Only the two loose-sheet maps are still written low-res.
const up = map => map.flatMap(row => { const r = row.split('').map(c => c + c).join(''); return [r, r]; });

const cache = new WeakMap();
export function sprite(map, over = {}) {
  let byMap = cache.get(map);
  if (!byMap) { byMap = new Map(); cache.set(map, byMap); }
  const key = JSON.stringify(over);
  let cv = byMap.get(key);
  if (!cv) {
    const pal = { ...BASE, ...over };
    cv = document.createElement('canvas');
    cv.width = Math.max(...map.map(r => r.length));
    cv.height = map.length;
    const g = cv.getContext('2d');
    map.forEach((row, j) => {
      for (let i = 0; i < row.length; i++) {
        const col = pal[row[i]];
        if (col) { g.fillStyle = col; g.fillRect(i, j, 1, 1); }
      }
    });
    byMap.set(key, cv);
  }
  return cv;
}

// Draws sprite(map, over) at logical (x, y); the HD sprite canvas is downscaled back to logical size.
export function blit(g, map, x, y, over) {
  const cv = sprite(map, over);
  g.drawImage(cv, x, y, cv.width / RES, cv.height / RES);
}

const mirror = map => map.map(row => row.split('').reverse().join(''));
const withFeet = (body, feet) => body.slice(0, -feet.length).concat(feet);

const SCRIBE_BACK = [
  '............kkkkkkkkkkkk........',
  '..........kkRRRRrrrrrrrrkk......',
  '........kkRRRrrzrzzrzrrrrdkk....',
  '.......kRRrrrrrrzzzzrrrrrrrdk...',
  '......kRrrrrrrrzzjjzzrrrrrrrdk..',
  '.....kRrrrrrrrrrzzzzrrrrrrrrrdk.',
  '....kRrrrrrrrrrzrzzrzrrrrrrrrddk',
  '....kRrrrrrrrrrrrrrrrrrrrrrrrddk',
  '....kRrrrrrrrrrkkkkkkrrrrrrrrddk',
  '....kRrrrrrrrrkmmmmmMkrrrrrrrddk',
  '....kRrrrrrrrrkmkOokMkrrrrrrrddk',
  '....kRrrrrrrrrkmkookMkrrrrrrrddk',
  '....kRrrrrrrrrkMmmmMMkrrrrrrrddk',
  '....kRrrrrrrrrrkkkkkkrrrrrrrrddk',
  '....kRrrrrrrrrrrkmMkrrrrrrrrrddk',
  '....kdRrrrrrrrrrkmMkrrrrrrrrdddk',
  '.....kdRrrrrrrrrkMMkrrrrrrrrddk.',
  '......kddrrrrrrrkmMkrrrrrrrddk..',
  '....kktzTTTTTTTTkmMkTTTTTTTTTTkk',
  '....kRrrrrrrrrrrkMMkrrrrrrrrrddk',
  '....kRmmrrrrrrrrkmMkrrrrrrrrmmdk',
  '....kRmMrrrrrrrrkmMkrrrrrrrrmMdk',
  '....kyyyyyyyyyyyyyyyyyyyyyyyyyyk',
  '....kyyyyyyyyyyyyyyyyyyyyyyyyyyk',
  '....kRrrrrrrrrrrrrrrrrrrrrrrdddk',
  '....kRrrrrrrrrrrrdrrrrrrdrrrdddk',
  '....kRrrrrrrrrrrRdrrrrrRdrrddddk',
  '....kdRrrrrrrrrrRdrrrrrRdrrddddk',
  '....kdRrrrrrrrrrRdrrrrrRdrdddddk',
  '....kddrrrrrrrrrRdrrrrrRdrdddddk',
  '.....kGgGgGgGgGgGgGgGgGgGgGgGk..',
  '......kkkkkkkkkkkkkkkkkkkkkkkk..',
  '.........kmmmmmMk..kmmmmmMk.....',
  '..........kkkkkk....kkkkkk......',
];
const SCRIBE_FRONT = [
  '............kkkkkkkkkkkk........',
  '..........kkRRRRrrrrrrrrkk......',
  '........kkRRRrrrrrrrrrrrrdkk....',
  '.......kRRrrrrrrrrrrrrrrrrrdk...',
  '......kRrrrrrrrrrrrrrrrrrrrrdk..',
  '.....kRrrrrrrrrrrrrrrrrrrrrrrdk.',
  '....kRrrrrrrttttttttttttrrrrrddk',
  '....kRrrrrRkkkkkkkkkkkkkkdrrrddk',
  '....kRrrrRkeeeeeeeeeeeeeekdrrddk',
  '....kRrrrRkeeeeeeeeeeeeeekdrrddk',
  '....kRrrrRkeeeOoeeeeOoeeekdrrddk',
  '....kRrrrRkeeeooeeeeooeeekdrrddk',
  '....kRrrrRkeeeeeeeeeeeeeekdrrddk',
  '....kRrrrRkeeeemMmMmMeeeekdrrddk',
  '....kRrrrRkeeeeeeeeeeeeeekdrrddk',
  '....kdRrrrRkkkkkkkkkkkkkkdrrdddk',
  '.....kdRrrrrrrrrrrrrrrrrrrrrddk.',
  '......kddrrrrrrrrrrrrrrrrrrddk..',
  '....kktzTTTTTTTTTTTTTTTTTTTTTTkk',
  '....kRrrrrrrrrrrzzzzrrrrrrrrrddk',
  '....kRlmrrrrrrrzzjjzzrrrrrrrlmdk',
  '....kRmMrrkyykrrzzzzrrrrrrrrmMdk',
  '....kyyyyyyyyyyyyyyyyyyyyyyyyyyk',
  '....kyyyyyyyyyyyyyyyyyyyyyyyyyyk',
  '....kRrrrkyyykrrrrrrrrrrrrrrdddk',
  '....kRrrrkykykrrrdrrrrrrdrrrdddk',
  '....kRrrrkykykrrRdrrrrrRdrrddddk',
  '....kdRrrrkrkrrrRdrrrrrRdrrddddk',
  '....kdRrrrrrrrrrRdrrrrrRdrdddddk',
  '....kddrrrrrrrrrRdrrrrrRdrdddddk',
  '.....kGgGgGgGgGgGgGgGgGgGgGgGk..',
  '......kkkkkkkkkkkkkkkkkkkkkkkk..',
  '.........klmmmmMk..klmmmmMk.....',
  '..........kkkkkk....kkkkkk......',
];
const SCRIBE_SIDE = [
  '............kkkkkkkkk...........',
  '..........kkRRRRrrrrkk..........',
  '........kkRRRrrrrrrrrrkk........',
  '.......kRRrrrrrrrrrrrrrrk.......',
  '......kRrrrrrrrrrrrrrrrrrk......',
  '......kRrrrrrrrrrrrrrrrrrrk.....',
  '......kRrrrrrrrrrrrttttttttk....',
  '......kRrrrrrrrrrRkkkkkkkkkk....',
  '......kRrrrrrrrrrRkeeeeeeeek....',
  '......kRrrrrrrrrrrkeeeeeeeek....',
  '......kRrrrrrrrrrrkeeeOoeeek....',
  '......kRrrrrrrrrrrkeeeooeeek....',
  '......kRrrrrrrrrrrkeeeeeeeek....',
  '......kRrrrrrrrrrrkeeeemMmMk....',
  '......kRrrrrrrrrrrkeeeeeeeek....',
  '......kdRrrrrrrrrrkkkkkkkkk.....',
  '.......kdRrrrrrrrrrrrrrrdk......',
  '........kddrrrrrrrrrrrrdk.......',
  '......kktzTTTTTTTTTTTTTTTkkk....',
  '......kRrrzzzzrrrrrrrrrrrddk....',
  '......kRrzzjjzzrrrrrdlmsssk.....',
  '......kRrrzzzzrrrrrrdmMssBk.....',
  '......kyyyyyyyyyyyyyyyyyyyyk....',
  '......kyyyyyyyyyyyyyyyyyyyyk....',
  '......kRrrrrrrrrrrrrrrrrrddk....',
  '......kRrrrrRdrrrrrRdrrrrddk....',
  '......kRrrrrRdrrrrrRdrrrdddk....',
  '......kdRrrrRdrrrrrRdrrrdddk....',
  '......kddRrrRdrrrrrRdrrddddk....',
  '......kddRrrRdrrrrrRdrrddddk....',
  '.......kGgGgGgGgGgGgGgGgGgk.....',
  '........kkkkkkkkkkkkkkkkkk......',
  '........klmmmMMkklmmmMMk........',
  '.........kkkkkk..kkkkkk.........',
];
// Walk cycle: each frame swaps the 2 HD feet rows under the hem.
const FEET = [
  ['.........klmmmmMk..klmmmmMk.....', '..........kkkkkk....kkkkkk......'],
  ['......klmmmmMk........kkkk......', '.......kkkkkk...................'],
  ['........kkkk........klmmmmMk....', '.....................kkkkkk.....'],
];
const FEET_SIDE = [
  ['........klmmmMMkklmmmMMk........', '.........kkkkkk..kkkkkk.........'],
  ['......klmmmMMk....klmmmMMk......', '.......kkkkkk......kkkkkk.......'],
  ['..........klmmmmmmmMMk..........', '...........kkkkkkkkkk...........'],
];
const RIGHT = FEET_SIDE.map(f => withFeet(SCRIBE_SIDE, f));
export const SCRIBE = {
  up: FEET.map(f => withFeet(SCRIBE_BACK, f)),
  down: FEET.map(f => withFeet(SCRIBE_FRONT, f)),
  right: RIGHT,
  left: RIGHT.map(mirror),
};

// Adept (one per subagent): 12x14 logical, bone robe with red hem trim, one green optic, data-slate.
const ADEPT_FRONT = [
  '........kkkkkkkk........',
  '......kkbbqqqqqqkk......',
  '.....kbbqqqJJJqqqQk.....',
  '....kbqqqqJJIJJqqqQk....',
  '....kbqqqqqJJJqqqqQk....',
  '....kbqqqkkkkkkqqqQk....',
  '....kbqqkeeeeeekqqQk....',
  '....kbqkeeeeeeeekqQk....',
  '....kbqkeeeeOceekqQk....',
  '....kbqkeeeecCeekqQk....',
  '....kbqkeemMmeeekqQk....',
  '....kQbqkkkkkkkkqQQk....',
  '...kkbqqqqqqqqqqqqQkk...',
  '...kbqQqqqqxqqqqqQqQk...',
  '...kbQqqqqqxqqqqqqQQk...',
  '...kbqkkkkkkkkkkqqqQk...',
  '...kblkmcCccCcmklqQQk...',
  '...kbmkmccCcccmkmqQQk...',
  '...kbqkkkkkkkkkkqqQQk...',
  '...kbqqqqqqxqqqqqqQQk...',
  '...kbqqqqqqxqqqqqqQQk...',
  '...kQbqqqqqxqqqqqqQQk...',
  '...kQQqqqqqxqqqqqQQQk...',
  '...kQQqqqqqxqqqqqQQQk...',
  '...kxxxxxxxxxxxxxxxxk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '.......kmmMk..kmmMk.....',
  '........kkk....kkk......',
];
const ADEPT_BACK = [
  '........kkkkkkkk........',
  '......kkbbqqqqqqkk......',
  '.....kbbqqqJJJqqqQk.....',
  '....kbqqqqJJIJJqqqQk....',
  '....kbqqqqqJJJqqqqQk....',
  '....kbqqqqqqqqqqqqQk....',
  '....kbqqqqqqqqqqqqQk....',
  '....kbqqqqqqQqqqqqQk....',
  '....kbqqqqqqQqqqqqQk....',
  '....kbqqqqqqQqqqqQQk....',
  '....kbqqqqqqQqqqqQQk....',
  '....kQbqqqqqqqqqqQQk....',
  '...kkbqqqqqqqqqqqqQkk...',
  '...kbqqqqqqqqqqqqqqQk...',
  '...kbqqqqxqxxqxqqqqQk...',
  '...kbqqqqqxxxxqqqqqQk...',
  '...kbqqqqxxkkxxqqqqQk...',
  '...kbqqqqqxxxxqqqqQQk...',
  '...kbqqqqxqxxqxqqqQQk...',
  '...kbqqqqqqqqqqqqqQQk...',
  '...kbqqqqqqqqqqqqqQQk...',
  '...kQbqqqqqqqqqqqqQQk...',
  '...kQQqqqqqqqqqqqQQQk...',
  '...kQQqqqqqqqqqqqQQQk...',
  '...kxxxxxxxxxxxxxxxxk...',
  '...kkkkkkkkkkkkkkkkkk...',
  '.......kmmMk..kmmMk.....',
  '........kkk....kkk......',
];
const ADEPT_SIDE = [
  '.......kkkkkkk..........',
  '.....kkbbqqqqqkk........',
  '....kbbqqJJJqqqqk.......',
  '....kbqqJJIJJqqqqk......',
  '....kbqqqJJJqqqqqqk.....',
  '....kbqqqqqqqqqkkkk.....',
  '....kbqqqqqqqqkeeek.....',
  '....kbqqqqqqqqkeeeek....',
  '....kbqqqqqqqqkeeOck....',
  '....kbqqqqqqqqkeecCk....',
  '....kbqqqqqqqqkemMek....',
  '....kQbqqqqqqqqkkkk.....',
  '....kkbqqqqqqqqqqQkk....',
  '....kbqqqqqqqqqqqqQk....',
  '....kbqqqqqqqqqqqqQk....',
  '....kbqqqqqqqqqqlkkkkk..',
  '....kbqqqqqqqqqqlkcCck..',
  '....kbqqqqqqqqqqQkkkkk..',
  '....kbqqqqqqqqqqqQQk....',
  '....kbqqqqqqqqqqqQQk....',
  '....kbqqqqqqqqqqqQQk....',
  '....kQbqqqqqqqqqqQQk....',
  '....kQQqqqqqqqqqQQQk....',
  '....kQQqqqqqqqqqQQQk....',
  '....kxxxxxxxxxxxxxxk....',
  '.....kkkkkkkkkkkkkk.....',
  '.......kmmMkkmmMk.......',
  '........kkk..kkk........',
];
const ADEPT_FEET = [
  ['.......kmmMk..kmmMk.....', '........kkk....kkk......'],
  ['.....kmmMk.....kkk......', '......kkk...............'],
  ['........kkk....kmmMk....', '................kkk.....'],
];
const ADEPT_FEET_SIDE = [
  ['.......kmmMkkmmMk.......', '........kkk..kkk........'],
  ['.....kmmMk....kmmMk.....', '......kkk......kkk......'],
  ['.........kmmmmMk........', '..........kkkkk.........'],
];
const ADEPT_RIGHT = ADEPT_FEET_SIDE.map(f => withFeet(ADEPT_SIDE, f));
export const ADEPT = {
  up: ADEPT_FEET.map(f => withFeet(ADEPT_BACK, f)),
  down: ADEPT_FEET.map(f => withFeet(ADEPT_FRONT, f)),
  right: ADEPT_RIGHT,
  left: ADEPT_RIGHT.map(mirror),
};

const ARM = [
  '.k..k...',
  'kl.kl...',
  'kl.km...',
  '.kkkMk..',
  '.klmMk..',
  '.kkkkk..',
  '..klMk..',
  '..kmMk..',
  '...kkkk.',
  '...klMk.',
  '...kmMk.',
  '..kkkkk.',
  '..klMk..',
  '.kmMk...',
  '.kkkk...',
  'klMk....',
];

export const MAPS = {
  ARM,
  ARM_L: mirror(ARM),
  SCROLL: [
    '.kkkkkkkkk..',
    'kbppppppPPk.',
    'kkkkkkkkkkk.',
    '.kpppppppPk.',
    '.kpPPPPPpPk.',
    '.kpppppppPk.',
    '.kpPPPkxxkk.',
    '.kppppxaxkk.',
    '.kpPPPkxxkk.',
    '.kpppppppPk.',
    '.kpPPPPppPk.',
    'kkkkkkkkkkk.',
    'kbppppppPPk.',
    '.kkkkkkkkk..',
  ],
  DESK: [
    '............kkkkkkkkkkkkkkkkkkkkkkkk..............F.............',
    '............khhhhhhhhhhhhhhhhhhhhhGk..............Ff............',
    '............khGggggggggggggggggggGGk.............fFFf...........',
    '............khgggGGGGGGGGGGGGGGgggGk.............fFFf...........',
    '............khgGkkkkkkkkkkkkkkkkggGk..............ff............',
    '............khgGkCCCCCCCCCCCCCCkggGk..............k.............',
    '............khgGkCccccCccccCCCCkggGk............kkkkkk..........',
    '............khgGkCCCCCCCCCCCCCCkggGk............kbppPk..........',
    '..kkkkkkkkkkkhgGkCcccCccCCCCCCCkggGk............kbppPk..........',
    '..kpbbbbbpPkkhgGkCCCCCCCCCCCCCCkggGk............pbppPk..........',
    '..kPPPPPPPPkkhgGkCccCccccCccccCkggGk............pbppPkkkkkk.....',
    '..kpppppppPkkhgGkCCCCCCCCCCCCCCkggGk............kbppPkkbpPk.....',
    '..kPPPPPPPPkkhgGkCcCccCccCCCCCCkggGk............kbppPkkppPk.....',
    '..kpppppppPkkhhGkCCCCCCCCCCCCCCkghGk............kbppPkkppPk.....',
    '..kPPPPPPPPkkhGGkkkkkkkkkkkkkkkkgGGk............kbppPkkppPk.....',
    '..kpppppppPkkhggggggGGGGGGGGggggggGk..........kkkkkkkkkkkkkk....',
    '..kPPPPPPPPkkGGGGGGGGGGGGGGGGGGGGGGk..........khhhhhhggGGGGk....',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..........kkkkkkkkkkkkkk....',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLkkkkkkkkkkLLLLLLLLLLLLk',
    'kwwwwwwwwwwwwwwwwwwwkkkkkkkkwwwwwwwwwwwwwkpppppppPkwwwwwwwwwwwwk',
    'kwwkkkkkkkWWWWWWwwwwkmmmmmmkwwwwwwwwwwwwwkpPPPPPpPkwwwwwwwwwwwwk',
    'kwwkPPPPpkwwwwwwwwwwkMmMmMMkwwWWWWWWWWWWWkpppppppPkwwwwwwwwwwwwk',
    'kwwkPPPPPkwwwwwwwwwwkkkkkkkkwwwwwwwwwwwwwkpPPPPPpPkwwwwwwwwwwwwk',
    'kwwkkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkWWWWWWWWWWwwk',
    'kwwwwwwwWWWWWWWWWWWWWWWwwwwwwwwwwwWWWWWWWwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkkkWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWGWWWWWWWWWWWkwwwwwwwwwwwwwwwwwwwwwwkWWWWWWWWWWWWWWWWWWWGWWWk',
    'kWWWWWWWWWWWWWWWkWWWWWWWWkkkkkkWWWWWWWWkWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWGWWWWWWWWWWWkWWWWWWWWkhhhhkWWWWWWWWkWWWWWWWWWWWWWWWWWWWGWWWk',
    'kWWWWWWWWWWWWWWWkWWWWWWWWkkkkkkWWWWWWWWkWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWWWWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkkkkkWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kmMMMk....................................................kmMMMk',
    'kmMMMk....................................................kmMMMk',
    'kmMMMk....................................................kmMMMk',
    'kmMMMk....................................................kmMMMk',
    'kkkkkk....................................................kkkkkk',
  ],
  // Compact lectern (22x21): the desk's slate and candle on a narrow body, for crowded halls (layout.js GRID.compact).
  LECTERN: [
    'kkkkkkkkkkkkkkkkkkkkkkkk..........F.........',
    'khhhhhhhhhhhhhhhhhhhhhGk..........Ff........',
    'khGggggggggggggggggggGGk.........fFFf.......',
    'khgggGGGGGGGGGGGGGGgggGk.........fFFf.......',
    'khgGkkkkkkkkkkkkkkkkggGk..........ff........',
    'khgGkCCCCCCCCCCCCCCkggGk..........k.........',
    'khgGkCccccCccccCCCCkggGk........kkkkkk......',
    'khgGkCCCCCCCCCCCCCCkggGk........kbppPk......',
    'khgGkCcccCccCCCCCCCkggGk........kbppPk......',
    'khgGkCCCCCCCCCCCCCCkggGk........pbppPk......',
    'khgGkCccCccccCccccCkggGk........pbppPkkkkkk.',
    'khgGkCCCCCCCCCCCCCCkggGk........kbppPkkbpPk.',
    'khgGkCcCccCccCCCCCCkggGk........kbppPkkppPk.',
    'khhGkCCCCCCCCCCCCCCkghGk........kbppPkkppPk.',
    'khGGkkkkkkkkkkkkkkkkgGGk........kbppPkkppPk.',
    'khggggggGGGGGGGGggggggGk......kkkkkkkkkkkkkk',
    'kGGGGGGGGGGGGGGGGGGGGGGk......khhhhhhggGGGGk',
    'kkkkkkkkkkkkkkkkkkkkkkkk......kkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLkkkkkkkkkkLLLLLLLLLLLLk',
    'kwwwwwwwwwwwwwwwwwwwwkpppppppPkwwwwwwwwwwwwk',
    'kwwkkkkkkkWWWWWWwwwwwkpPPPPPpPkwwwwwwwwwwwwk',
    'kwwkPPPPpkwwwwwwwwwwwkpppppppPkwwwwwwwwwwwwk',
    'kwwkPPPPPkwwwwwwwwwwwkpPPPPPpPkwwwwwwwwwwwwk',
    'kwwkkkkkkkwwwwwwwwwwwkkkkkkkkkkWWWWWWWWWWwwk',
    'kwwwwwwwWWWWWWWWWWWWWwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkWWWWWWWWWWWk',
    'kWWWGWWWWWWWkwwwwwwwwwwwwwwwwwwkWWWWWWGWWWWk',
    'kWWWWWWWWWWWkWWWWWWkkkkkkWWWWWWkWWWWWWWWWWWk',
    'kWWWGWWWWWWWkWWWWWWkhhhhkWWWWWWkWWWWWWGWWWWk',
    'kWWWWWWWWWWWkWWWWWWkkkkkkWWWWWWkWWWWWWWWWWWk',
    'kWWWWWWWWWWWkkkkkkkkkkkkkkkkkkkkWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kmMMMk................................kmMMMk',
    'kmMMMk................................kmMMMk',
    'kmMMMk................................kmMMMk',
    'kmMMMk................................kmMMMk',
    'kkkkkk................................kkkkkk',
  ],
  SHELF: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLk',
    'kLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kLgWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWgWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLWknnnnnnnnnnnnnnnnnnnkkkkknnnnnnnnnnkkkkkkknnnnnnnnnnnnnnnkWWk',
    'kLWknnnnnkkknnnnnkkkkknppppPnkkkknnnnnPPPBxxrnkkkkkkkkkknnnnkWWk',
    'kLWkkkkknxxrnnnnnuuuunnggggPnPPPBkkkkngggBxxrnxxxrppPuunnnnnkWWk',
    'kLWkpppPnxxrnkkkkuuuunnppppPnPPPBvvvnnPPPBxxrngggrppPuunnkknkWWk',
    'kLWkpppPnxxrnxxxruuuunnppppPnPPPBgggnnPPPBxxrnxxxrppPuunnuunkWWk',
    'kLWkpppPnxxrngggruuuunnppppPnPPPBvvvnnPPPBxxrnxxxrppPuunnuunkWWk',
    'kLWkpppPnxxrnxxxruuuunnppppPnPPPBvvvnnPPPBxxrnxxxrppPuunnuunkWWk',
    'kLWkpppPnxxrngggruuuunnggggPnPPPBgggnngggBxxrngggrppPuunnuunkWWk',
    'kLWkpppPnxxrnxxxruuuunnppppPnPPPBvvvnnPPPBxxrnxxxrppPuunnuunkWWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLWknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnkkkknnnnnnkkkknnnnnnkWWk',
    'kLWkkkkkknnkknkkkknkkknnnnnnnnnkkknnnnnnxxxrnnnnnkbbbbknnnnnkWWk',
    'kLWkxxxxrnnuunuuunnvvvnnnnkkkknppPnkkkkkgggrnnnnnkkbkbknnnnnkWWk',
    'kLWkggggrnnuunuuunnvvvnkkkuuuunppPnppppPxxxrnppppkbbbBkppknnkWWk',
    'kLWkxxxxrnnuunuuunnvvvnxxruuuunppPnggggPxxxrnPPPPPkBkkPPPknnkWWk',
    'kLWkxxxxrnnuunuuunnvvvnxxruuuunppPnppppPxxxrnuuuuuuuuuuuknnnkWWk',
    'kLWkxxxxrnnuunuuunnvvvnxxruuuunppPnppppPxxxrnnnnnnnnnnnnknnnkWWk',
    'kLWkggggrnnuunuuunnvvvnxxruuuunppPnggggPgggrnxxxxxxxxxxxxxknkWWk',
    'kLWkxxxxrnnuunuuunnvvvnxxruuuunppPnppppPxxxrnrrrrrrrrrrrrrknkWWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLWWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLWkkkkkkkknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnkkkknkkkkkkWWk',
    'kLWkPPBpppPnnnnnnnnnnnnnnnnnnnnnnnnnnkkknkkknkkkknpppPnPPPBBkWWk',
    'kLWkPPBgggPnkkkkkkkkknnnnnnnnnnnnkkknxxrnuuunuuuungggPnPPPBBkWWk',
    'kLWkPPBpppPnxxxrvvvvnnkkkkknkkkknvvvnxxrngggnuuuunpppPnPPPBBkWWk',
    'kLWkPPBpppPngggrvvvvnnvvvvnnvvvnnvvvnxxrnuuunuuuunpppPnPPPBBkWWk',
    'kLWkPPBpppPnxxxrvvvvnnvvvvnngggnnvvvnxxrnuuunuuuunpppPnPPPBBkWWk',
    'kLWkPPBpppPnxxxrvvvvnnvvvvnnvvvnnvvvnxxrnuuunuuuunpppPnPPPBBkWWk',
    'kLWkPPBgggPngggrvvvvnnvvvvnngggnnvvvnxxrngggnuuuungggPnPPPBBkWWk',
    'kLWkPPBpppPnxxxrvvvvnnvvvvnnvvvnnvvvnxxrnuuunuuuunpppPnPPPBBkWWk',
    'kLWkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkWWk',
    'kLgLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLgWk',
    'kLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  SKULL: [
    '......kkkkkkkk......',
    '....kkbbbbbbbbkk....',
    '...kbbbbbbbbbbbbk...',
    '..kbbbbbbbbbbbbbBk..',
    '..kbbbbbbbbbbbbbBk..',
    '.kbkkkkbbbbkkkkbBBk.',
    '.kbkOokbbbbkkkkbbBk.',
    '.kbkookbbbbkkkkbbBk.',
    '.kbbbbbbbkkbbbbbbBk.',
    '..kbbbbbbkkbbbbbBk..',
    '...kbbbbbbbbbbbBk...',
    '...kbkbkbkbkbkbk....',
    '....kkkkkkkkkkkk....',
    '.....khggggggGk.....',
    '.....kgkMMMMkGk.....',
    '.....kgMlmMMMGk.....',
    '......kgMMMMGk......',
    '.......kggGGk.......',
    '........kGGk........',
    '.........kk.........',
  ],
  COG_MECH: [
    '.................kkkkkk.................',
    '................kbbbbbbk................',
    '................kbbbbbbk................',
    '.........kk.....kbbbbbbk.....kk.........',
    '........kbbk...kkbbbbbbkk...kbbk........',
    '.......kbbbbkkkbbbbbbbbbbkkkbbbbk.......',
    '......kbbbbbkbbbbbbbbbbbbbbkbbbbbk......',
    '.....kbbbbbbbbbbbbbBBbbbbbbbbbbbbbk.....',
    '.....kbbbbbbbbbBBBBBBBBBBbbbbbbbbbk.....',
    '......kbbbbbbbBBBBBkkBBBbbbbbbbbbk......',
    '.......kkbbbbBBBkkkkkkkkbbbbbbbkk.......',
    '.......kbbbbBBkkbbbbbblmkkbbbbbbk.......',
    '.......kbbbBBkbbbbbbbblmmMkbbbbBk.......',
    '......kbbbBBBkbbbbbbbblmmmMkbBBBBk......',
    '...kkkkbbbBBkbbbbbbbbblmmmMkbbBBBkkkk...',
    '..kbbbbbbbBBkbbkkkkbbblkkkMkbbBBBBBBBk..',
    '..kbbbbbbbBBkbkkkkkkbbkkOokkbbBBBBBBBk..',
    '..kbbbbbbBBkkbkkkkkkbbkoooMkkbBBBBBBBk..',
    '..kbbbbbbBBkkbbkkkkbbblkkkMkkbBBBBBBBk..',
    '..kbbbbbbbBBkbbbbbbkbblmmmMkbbBBBBBBBk..',
    '..kbbbbbbbBBkkbbbbkkkblmmMkkbbBBBBBBBk..',
    '...kkkkbbbBBkkBbbbbbbblmmMkkbbBBBkkkk...',
    '......kbbbBbbkkBbbbbbblmMkkbbBBBBk......',
    '.......kbbbbbkkbkbkbkbkmkkkbbBBBk.......',
    '.......kbbbbbbkbkbkbkbkMkkbbBBBBk.......',
    '.......kkbbbbbbkkkkkkkkkkbbBBBBkk.......',
    '......kbbbbbbbbbbbbkkbbbbbBBBBBBBk......',
    '.....kbbbbbbbbbBbbbbbbbbBBBBBBBBBBk.....',
    '.....kbbbbbbbbbBBBBBBBBBBBBBBBBBBBk.....',
    '......kbbbbbkbBBBBBBBBBBBBBkBBBBBk......',
    '.......kbbbbkkkBBBBBBBBBBkkkBBBBk.......',
    '........kbbk...kkBBBBBBkk...kBBk........',
    '.........kk.....kBBBBBBk.....kk.........',
    '................kBBBBBBk................',
    '................kBBBBBBk................',
    '.................kkkkkk.................',
  ],
  SEAL: [
    '...kkkkkk...',
    '..kxxxxxxk..',
    '.kxxkkkkxxk.',
    '.kxkhggGkrk.',
    '.kxkgggGkrk.',
    '.kxxkkkkxrk.',
    '..kxrrrrrk..',
    '...kkkkkk...',
    '..kppppPk...',
    '..kpPPPPk...',
    '..kppppPk...',
    '..kpPPpPk...',
    '..kppppPk...',
    '..kpPPPPk...',
    '..kppppPk...',
    '..kpPpPPk...',
    '..kppppPk...',
    '..kppkpPk...',
    '..kpk.kPk...',
    '..kk...kk...',
  ],
  CANDLES: [
    '....F.......F...........',
    '...fFf.....fFf..........',
    '...fFFf....fFFf.....F...',
    '...fFFf....fFFf....fFf..',
    '....ff......ff.....fFFf.',
    '....k.......k......fFFf.',
    '..kkkkkk..kkkkkk....ff..',
    '..kbbbbk..kbbbbk....k...',
    '..kbppPk..kbppPk..kkkkkk',
    '..kbppPp..kbppPk..kbbbbk',
    '..kbppPpk.kbppPk..kbppPk',
    '..kbppPkk.kbppPPk.kbppPk',
    '..kbppPk..kbppPk..kbppPk',
    '.kkbppPkkkkbppPkkkkbppPk',
    'kpkbppPkppkbppPkppkbppPk',
    'kPkbkkPkPPkbkkPkPPkbkkPk',
    'kPPPPPPPPPPPPPPPPPPPPPPk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  THRONE: [
    '.................kkkkkk.................',
    '................kbbbbbbk................',
    '...........kk..kbbbbbbbbk..kk...........',
    '..........klMk.kbkkbbkkbk.kMMk..........',
    '..........klmMkkbkkbbkkbkkMmMk..........',
    '...........klMk.kbbkkbbk.kMMk...........',
    '............klk.kBbbbbBk.kMk............',
    '.............kk..kbkkbk..kk.............',
    '........kkkkkkkkkkkkkkkkkkkkkkkk........',
    '........khhhhhhhhhhhGGGGGGGGGGGk........',
    '........kggggggggggggggggggggggk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '........khgrxxdxxxdxxdxxxdxxrgGk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '........khgrxxxxdxxxxxxdxxxxrgGk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '........khgrxxdxxxdxxdxxxdxxrgGk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '........khgrxxxxdxxxxxxdxxxxrgGk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '........khgrxxdxxxdxxdxxxdxxrgGk........',
    '........khgrxxxxxxxxxxxxxxxxrgGk........',
    '..kkkkkkkhgrxxxxdxxxxxxdxxxxrgGkkkkkkk..',
    '..klllMkkhgrxxxxxxxxxxxxxxxxrgGkkMMMMk..',
    '..kmmmMkkhgrxxdxxxdxxdxxxdxxrgGkkMmmmk..',
    '..kmmmMkkhgrxxxxxxxxxxxxxxxxrgGkkMmmmk..',
    '..kmmmMkkhgrxxxxdxxxxxxdxxxxrgGkkMmmmk..',
    '..kkkkkkkhgrkkkkkkkkkkkkkkkkrgGkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..khhhhhhhhhhhhhhhhhGGGGGGGGGGGGGGGGGk..',
    '..kggggggggggggggggggggggggggggggggggk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '....kxxxxxdxxxxxxxxxxxxxxxxxxdxxxxxk....',
    '....kxxxxxdxxxxxxxxxxxxxxxxxxdxxxxxk....',
    '....krrrrrrrrrrrrrrrrrrrrrrrrrrrrrrk....',
    '....kggggggggggggggggggggggggggggggk....',
    '....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
    '....kmMMk......................kMMmk....',
    '....kmMMk......................kMMmk....',
    '....kkkkk......................kkkkk....',
  ],
  MAGOS: [ // seated Magos; scene.js swings art cols 0..9 (drill forearm)
    '.............kkkk...............................',
    '...........kkhhggkk.............................',
    '..klmMk...khhgggggGk............................',
    '..klmMkkkkkhgMMMMgGk............................',
    '..klmMklmMMggMlMMGGk............................',
    '..khgGkkkkkggMMMMGGk............................',
    '..klmMk...kGgggGGGGk............................',
    '..klmMk....kkGGGGkk.............................',
    '..klmMk......kkkk...............................',
    '..klmMk.....kllmMk..............................',
    '..khgGk.....khggGk..............................',
    '..klmMk.....kllmMk..............................',
    '..klmMk.....kllmMk..............................',
    '..klmMk.....kllmMk......kkkkkkkk................',
    '..klmMk.....kllmMk....kkRRrrrrddkk..............',
    '.khggGGk....khggGk...kRRrrrrrrrrddk.............',
    '.kGGGGGk....kllmMk..kRrrkkkkkkkkrrdk............',
    '.kllmmMk....kllmMk..kRrkeeeeeeeekrdk............',
    '.kmllmMk....kllmMk..kRrkeeeeeeeekrdk............',
    '..kmllk.....kllmMk..kRrkeoceecoekrdk............',
    '..kMmlk......kkkk...kRrkeCeeeeCekrdk............',
    '...klk.....kkhhggkk.kRrkeemMMmeekrdk............',
    '...kmk....khhgggggGkkdRrkemMMmekrddk............',
    '....k.....khgMMMMgGkkdRrrkkkkkkrrddkk...........',
    '..........kggMlMMGGkRRrrMrrrrrrMrrrddkkk........',
    '..........kggMMMMGGkrrrrMrrrrrrMrrrrrdkMMk......',
    '..........kGgggGGGGkrrrrMrrrrrrMrrrrrr.kmMMk....',
    '...........kkGGGGkk.rrrrMrrrrrrMrrrrrr...kmMk...',
    '.............kkkk...rdrrMrrrrrrMrrdrrrrddkkmMk..',
    '..............kRrrrrdkrrkmmmmmMkrrkdrrrddkkmMk..',
    '..............kRrrrrdkrrkmCcOcMkrrkdrrrddkkmMk..',
    '..............kRrrrrdkrrkmcCcCMkrrkdrrrddkkmMk..',
    '..............kRrrrrdkrrkmCcccMkrrkdrrrddkkmMk..',
    '..............kRrrrrdkrrkMMMMMMkrrkdrrrddkhggGk.',
    '..............kRrrrrdkrrrrrrrrrrrrkdrrrddkMkkMk.',
    '..............kRrrrrdkgglgGhhGglggkdrrrddkl..lk.',
    '..............kRhhggGkRrMrrrrrrMrdkhhggGd.k..k..',
    '...............kllmMk.kmmkrrrkhhgk.kllmMk.......',
    '...............kmkmk..kFfkrrrkcgck..kmkmk.......',
    '..................kRRrkfFkrddkgGGkrddk..........',
    '..................kRrRkffkrdd.kGk.rddk..........',
    '..................kRrrkmmkrddrrrrrrddk..........',
    '..................kRrr.kk.rddrdrrrrddk..........',
    '..................kdRrrrdrrddrrdrrdddk..........',
    '...................kdrdrdrdddrdrdrddk...........',
    '...................kkdkMMkkkkkkMMkdkk...........',
    '......................kMMk....kMMk..............',
    '......................kkkk....kkkk..............',
  ],
  LORD_DESK: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'khhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhk',
    'kggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggk',
    'kLLLLLLLLLLLkkkkkkkkkkLLLLLLLLkkkkkkkkkkkkkkLLLLLLLLLLLLkkkkkkLLLLLLLLLLLLkkkkkkLLLLLLLk',
    'kwwwwwwwwwwwkpppppppPkwwwwwwwwkCCCCCCCCCCoCkwwwwwwwwwwwwkpppPkwwwwwwwwwwwwklllmkwwwwwwwk',
    'kwwWWWWWWWWwkpPPPPPpPkwwwwwwwwkCccccccccCCCkwwwwwwwwwwwwkPPPPkwwwwwwwwwwwwkMeeMkWWWWWWwk',
    'kwwwwwwwwwwwkpppaxppPkwwwwwwwwkCCCCCCCCCCCCkwwWWWWWWWWWwkpppPkwwwwwwwwwwwwkMeeMkwwwwwwwk',
    'kwwwwwwwwwwwkpPPxxPpPkwwwwwwwwkCcccccCCCCCCkwwwwwwwwwwwwkpppPkwwwwwwwwwwwwkMMMMkwwwwwwwk',
    'kwwwwwwwwwwwkpppppppPkwwWWWWWWkCCCCCCCCCCCCkwwwwwwwwwwwwkpppPkwwWWWWWWWWWwkkkkkkwwwwwwwk',
    'kwwwwwwwwwwwkkkkkkkkkkwwwwwwwwkkkkkkkkkkkkkkwwwwwwwwwwwwkkkkkkwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'khhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhk',
    'kggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkkkkkkkkkkkkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kWWWnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnWWWkbbbbbbbbbmmmkWWWnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnWWWk',
    'kWWWnWWWWWWWWWWWWWWWWWWWWWWWWWWWWwWWkbbkkkbbbbmkkoMkWWnWWWWWWWWWWWWWWWWWWWWWWWWWWWWwWWWk',
    'kWWWnWWggggggggggggggggggggggggWWwWWkbbkkkbbbbmkkoMkWWnWWggggggggggggggggggggggggWWwWWWk',
    'kWWWnWWGGGGGGGGGGGGGGGGGGGGGGGGWWwWWWkbbbbbkbbbmmmkWWWnWWGGGGGGGGGGGGGGGGGGGGGGGGWWwWWWk',
    'kWWWnWWWWWWWWWWWWWWWWWWWWWWWWWWWWwWWWWkbkbkbkkmkmkWWWWnWWWWWWWWWWWWWWWWWWWWWWWWWWWWwWWWk',
    'kWWWnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWWWWWkkkkkkkkkkWWWWWnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwWWWk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'khhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhk',
    'kggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggk',
    'kGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  BRAZIER: [
    '........F...........',
    '........FF..........',
    '.......fFF.f........',
    '......ffFFff........',
    '.....fffFFfff.......',
    '.....ffFFFFff.......',
    '....kafFFFFfak......',
    '..khhggggggggGGk....',
    '...kggggggggGk......',
    '....kGGGGGGGGk......',
    '.....kkGGGGkk.......',
    '.......khGk.........',
    '.......khGk.........',
    '.......klMk.........',
    '.......kmMk.........',
    '.......khGk.........',
    '.......khGk.........',
    '.......khGk.........',
    '.......khGk.........',
    '......kkhGkk........',
    '.....khhggGGk.......',
    '....khggggggGk......',
    '...khgggggggGGk.....',
    '..khggggggggGGGk....',
    '..kGGGGGGGGGGGGk....',
    '..kkkkkkkkkkkkkk....',
  ],
  RECAFF: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'klllllllllllllllllllllllllllllMk',
    'klmmmmmmmmmmmmmmmmmmmmmmmmmmmmMk',
    'klmkkkkkkkkkkkkkkkkkkkkkkkkkkmMk',
    'klmkhhhhhhhhhhhhhhhhhhhhhhhGkmMk',
    'klmkgkggggggggggggggggggggkGkmMk',
    'klmkggkkkkkkkkkkkkkkkkkkkkgGkmMk',
    'klmkggkbBBBBBBBBbBBBBBBbbkgGkmMk',
    'klmkggkkkkkkkkkkkkkkkkkkkkgGkmMk',
    'klmkgkggggggggggggggggggggkGkmMk',
    'klmkGGGGGGGGGGGGGGGGGGGGGGGGkmMk',
    'klmkkkkkkkkkkkkkkkkkkkkkkkkkkmMk',
    'klmmmmmmmmmmmmmmmmmmmmmmmmmmmmMk',
    'klmkkkkkkkkkkkkkkkkkmmmmmmmmmmMk',
    'klmkCCCCCCCCCCCCCCCkmmkkkkmmmmMk',
    'klmkCcCccCccCccCCCCkmmkaakmmmmMk',
    'klmkCCCCCCCCCCCCCCCkmmkaakmmmmMk',
    'klmkCcCccCccCccCccCkmmkkkkmmmmMk',
    'klmkCCCCCCCCCCCCCCCkmmkkkkmmmmMk',
    'klmkCcCccCccCCCCCCCkmmkookmmmmMk',
    'klmkCCCCCCCCCCCCCCCkmmkookmmmmMk',
    'klmkkkkkkkkkkkkkkkkkmmkkkkmmmmMk',
    'klmmmmmmmmmmmmmmmmmmmmmmmmmmmmMk',
    'klmmmmmmmkkkkkkkkkkkkkmmmmmmmmMk',
    'klmmmmmmmkneeekkkeeeekmmmmmmmmMk',
    'klmmmmmmmkneeeeWeeeeekmmmmmmmmMk',
    'klmmmmmmmknekkkkkkkeekmmmmmmmmMk',
    'klmmmmmmmknekWWWWBkbekmmmmmmmmMk',
    'klmmmmmmmknekbbbbBkkekmmmmmmmmMk',
    'klmmmmmmmknekkkkkkkeekmmmmmmmmMk',
    'klmmmmmmmkkkkkkkkkkkkkmmmmmmmmMk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kMmmmmmmmmmmmmmmmmmmmmmmmmmmmmMk',
    'kMMlMMMMMMMMMMMMMMMMMMMMMMMMlMMk',
    'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  // Adept's cogitator terminal (14x10 logical): brass-framed phosphor screen, brass keys, iron stand, floor cable.
  CONSOLE: [
    '...kkkkkkkkkkkkkkkkkkkkkk...',
    '...khhhhhhhhhhhhhhhhhhhGk...',
    '...khkkkkkkkkkkkkkkkkkgGk...',
    '...khkCcCcCCcCCCCCCCCkgGk...',
    '...khkCCCCCCCCCCCCCCCkgGk...',
    '...khkCccCcCCcccCCCCCkgGk...',
    '...khkCCCCCCCCCCCCCCCkgGk...',
    '...khkCcCcccCcCCcCCCCkgGk...',
    '...khkCCCCCCCCCCCCCCCkgGk...',
    '...khkCcccCCcCCCCCcCCkgGk...',
    '...khgkkkkkkkkkkkkkkkggGk...',
    '...kGGGGGGGGGGGGGGGGGGGGk...',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkk.',
    'kmhkhkhkhkhkhkhkhkhkhkhkhmMk',
    'kmGkGkGkGkGkGkGkGkGkGkGkGmMk',
    'kmmmmmmmmmmmmmmmmmmmmmmmmmMk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '..........kmMMMMk.......kMk.',
    '.........kmMMMMMMk......kMk.',
    '.........kkkkkkkkk.......kk.',
  ],
  COGITATOR: [
    '...............................................................................khhhhk...............................................................................',
    '...............................................................................khhhhk...............................................................................',
    '.........................................................................kk....khhhgk....kk.........................................................................',
    '........................................................................khhk.kkhhhgggkk.kggk........................................................................',
    '.......................................................................khhhkkhhhhggggggkkgggk.......................................................................',
    '......................................................................khhhhhhhhhgggggggggggggk......................................................................',
    '....................................kkkkkkkkkkkkkkkkk..................khhhhhhhkkkkkgggggGggk..................kkkkkkkkkkkkkkkkk....................................',
    '...................................kkkkkkkkkkkkkkkkkkk..................khhhhkkGGGGGkkgggGGk..................kkkkkkkkkkkkkkkkkkk...................................',
    '..................................kkkkkkkkkkkkkkkkkkkkk.................khhhkGkkkkkkGGkgggGk.................kkkkkkkkkkkkkkkkkkkkk..................................',
    '...................................kklllllllllllllllkk.................khhhkGkbbbbbbkGGkgggGk.................kklllllllllllllllkk...................................',
    '...................................kkMMMMMMMMMMMMMMMkk.................khhhkkbbbbbbbbkGkgggGk.................kkMMMMMMMMMMMMMMMkk...................................',
    '...................................kkMkkkkkkkkkkkkkMkk...............kkkhhkkbkkbbbbkkbkGkggGkkk...............kkMkkkkkkkkkkkkkMkk...................................',
    '...................................kkMMMMMMMMMMMMMMMkk..............khhhhgkkbkaabbaakbkGkggGgggk..............kkMMMMMMMMMMMMMMMkk...................................',
    '...................................kkMkkkkkkkkkkkkkMkk.............khhhhggkkbbbbkkbbbBkGkgggGgggk.............kkMkkkkkkkkkkkkkMkk...................................',
    '...................................kkMMMMMMMMMMMMMMMkk..............khhgggkGkbbbbbbbBkGGkggGgggk..............kkMMMMMMMMMMMMMMMkk...................................',
    '..........kkkkkkkkkkkkkkkkkkkkkkkkkkkMkkkkkkkkkkkkkMkkkkkkkkkkkkkkkkkkkkggkGGkbkbkbBkGGGkggGkkkkkkkkkkkkkkkkkkkkMkkkkkkkkkkkkkMkkkkkkkkkkkkkkkkkkkkkkkkkkk..........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgggkGGkkkkkkGGGkgggGkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '.........kkhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhgggkGGGGGGGGGGGkgggGhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhkk.........',
    '.........kkgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggkGGGGGGGGGkgggGggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggkk.........',
    '.........kkggghggggggghggggggghggggggghggggggghggggggghggggggghggggggghggggggkkGGGGGkkgggGGggghggggggghggggggghggggggghggggggghggggggghggggggghggggggghggkk.........',
    '.........kkggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggGgggkkkkkggggGGgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggkk.........',
    '.........kkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGggggGGggggggggggGGggggGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkk.........',
    '.........kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgggkkGGggggggGGkkgggkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.........',
    '.........kklmmmmmmmmmmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMggMMMMGGGGGGMMMMggMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmmmmmmmmmmMkk.........',
    '.........kklmmmmmmmmmmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMggggMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmmmmmmmmmmMkk.........',
    '.........kklmmmmkkkkkmmmmmMkGgMMhkkkkkkkkkkkkkkkkkkkkkkkkhMMkMMMhkkkkkkkkkkkkkkkggggkkkkkkkkkkkkkkkhMMMkMMhkkkkkkkkkkkkkkkkkkkkkkkkhMMgGklmmmmkkkkkmmmmmMkk.........',
    '.........kklmmkkmmmmmkkmmmMkGgMMkhhhhhhhhhhhhhhhhhhhhhhhGkMMkMMMkhhhhhhhhhhhhhhhgggghhhhhhhhhhhhhhGkMMMkMMkhhhhhhhhhhhhhhhhhhhhhhhGkMMgGklmmkkmmmmmkkmmmMkk.........',
    '.........kklmkmmWWWWWmmkmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmkmmWWWWWmmkmmMkk.........',
    '.........kklkmlWWWWWWWmmkmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklkmlWWWWWWWmmkmMkk.........',
    '..kkkkkkkkklkmWWWWWWWWWmkmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklkmWWWWWWWWWmkmMkkkkkkkkk..',
    '.kkMkkxkkGkkmWWWWgggWWWWmkMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGkkmWWWWgggWWWWmkMkGkkxkkMkk.',
    '.kkmkkxkkgkkmWWWghgggWWWmkMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGkkmWWWghgggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWggkggWWWmkMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGkkmWWWggkggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWgggggWWWmkMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGkkmWWWgggggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWWgggWWWWmkMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGkkmWWWWgggWWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgklkmWWWWWWWWWmkmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklkmWWWWWWWWWmkmMkgkkxkkmkk.',
    '.kkmkkxkkgklkmmWWWWWWWmmkmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklkmmWWWWWWWmmkmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkmmWWWWWmmkmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmkmmWWWWWmmkmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmkkmmmmmkkmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmkkmmmmmkkmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmkkkkkmmmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmmmkkkkkmmmmmMkgkkxkkmkk.',
    'khhhhhhhhhklmmmmmeeemmmmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmmmmeeemmmmmmMkhhhhhhhhhk',
    'kgggggggggklmmmmmeeemmmmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmmmmeeemmmmmmMkgggggggggk',
    'kkkkkkkkkkklmmmmmeeemmmmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmmmmeeemmmmmmMkkkkkkkkkkk',
    'kkkmkkxkkgklmmmmmeeemmmmmmMkGgMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkhCCCCCCCCCCCCCCCCCCCCCCGkMMgGklmmmmmeeemmmmmmMkgkkxkkmkkk',
    '.kkmkkxkkgklmmmmmeeemmmmmmMkGgMMkGGGGGGGGGGGGGGGGGGGGGGGGkMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMkGGGGGGGGGGGGGGGGGGGGGGGGkMMgGklmmmmmeeemmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmeeemmmmmmMkGgMMhkkkkkkkkkkkkkkkkkkkkkkkkhMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMhkkkkkkkkkkkkkkkkkkkkkkkkhMMgGklmmmmmeeemmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmeeemmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmeeemmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmkkkkkmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmkkkkkmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmkkmmmmmkkmmmMkGgMMMMMMMkkkkkMMMMMMkkkkkMMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMMkkkkkMMMMMMkkkkkMMMMMMMgGklmmkkmmmmmkkmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkmmWWWWWmmkmmMkGgMMMMMMkgggggkMMMMkgggggkMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMkRxxxxkMMMMkRxxxxkMMMMMMgGklmkmmWWWWWmmkmmMkgkkxkkmkk.',
    '.kkmkkxkkgklkmlWWWWWWWmmkmMkGgMMMMMkgghbbggkMMkgghbbggkMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMkxxxxxxxkMMkxxxxxxxkMMMMMgGklkmlWWWWWWWmmkmMkgkkxkkmkk.',
    '.kkmkkxkkgklkmWWWWWWWWWmkmMkGgMMMMkggbbbbxggkkggbbbbxggkMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMkxxxMxMxxxkkxxxMxMxxxkMMMMgGklkmWWWWWWWWWmkmMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWWgggWWWWmkMkGgMMMMkgbbbbxbbgkkgbbbbxbbgkMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMkxxMMxMMxxkkxxMMxMMxxkMMMMgGkkmWWWWgggWWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWghgggWWWmkMkGgMMMMkgBbbMbbBgkkgBbbMbbBgkMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMkxxxxhxxxxkkxxxxhxxxxkMMMMgGkkmWWWghgggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWggkggWWWmkMkGgMMMMkgbbbbbbbgkkgbbbbbbbgkMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMkxxMMxMMxxkkxxMMxMMxxkMMMMgGkkmWWWggkggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWgggggWWWmkMkGgMMMMkggbbbbbggkkggbbbbbggkMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMkxxxMxMxxxkkxxxMxMxxxkMMMMgGkkmWWWgggggWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgkkmWWWWgggWWWWmkMkGgMMMMMkggbbbggkMMkggbbbggkMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMkxxxxxxxkMMkxxxxxxxkMMMMMgGkkmWWWWgggWWWWmkMkgkkxkkmkk.',
    '.kkmkkxkkgklkmWWWWWWWWWmkmMkGgMMMMMMkgggggkMMMMkgggggkMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMkxxxxxkMMMMkxxxxxkMMMMMMgGklkmWWWWWWWWWmkmMkgkkxkkmkk.',
    '.kkmkkxkkgklkmmWWWWWWWmmkmMkGgMMMMMMMkkkkkMMMMMMkkkkkMMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMMkkkkkMMMMMMkkkkkMMMMMMMgGklkmmWWWWWWWmmkmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkmmWWWWWmmkmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkhCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGkMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmkmmWWWWWmmkmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmkkmmmmmkkmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmkkmmmmmkkmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmkkkkkmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMhkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkhMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmkkkkkmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMMkkkMkbkMkbkMkkkMkbkMkbkMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkkkMkbkMkbkMkkkMkbkMkbkMMMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMMkkkMklkMklkMkkkMklkMklkMMMMkMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMkMMMkkkMklkMklkMkkkMklkMklkMMMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMMkbkMkkkMkkkMkbkMkkkMkkkMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMkbkMkkkMkkkMkbkMkkkMkkkMMMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkkkkkkkkkkkkmMkGgMMMklkMkMkMkMkMklkMkMkMkMkMMMMkMMMMMaaMMMooMMMffMMMooMMMaaMMMooMMMffMMMMMkMMMklkMkMkMkMkMklkMkMkMkMkMMMMgGklmkkkkkkkkkkkkmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMMkkkMkkkMkkkMkkkMkkkMkkkMMMMkMMMMMaaMMMooMMMffMMMooMMMaaMMMooMMMffMMMMMkMMMkkkMkkkMkkkMkkkMkkkMkkkMMMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkkkkkkkkkkkkmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmkkkkkkkkkkkkmMkgkkxkkmkk.',
    'khhhhhhhhhklmmmmmmmmmmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmmmmmmmmmmMkhhhhhhhhhk',
    'kgggggggggklmkkkkkkkkkkkkmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmkkkkkkkkkkkkmMkgggggggggk',
    'kkkkkkkkkkklmmmmmmmmmmmmmmMkGgMMkkkkkkkkkkkkkkkkkkkkkkkkkkMMkMMMMMMMMMMMMMMMkkkkkkkkkkkkMMMMMMMMMMMMMMMkMMkkkkkkkkkkkkkkkkkkkkkkkkkkMMgGklmmmmmmmmmmmmmmMkkkkkkkkkkk',
    'kkkmkkxkkgklmkkkkkkkkkkkkmMkGgMMkbbbbbbbbbbbbbbbbbbbbbbbbkMMkMMMMMkkkkkkkkkkkhhhhhhhhhhkkkkkkkkkkkMMMMMkMMkbbbbbbbbbbbbbbbbbbbbbbbbkMMgGklmkkkkkkkkkkkkmMkgkkxkkmkkk',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMkbbBBBBBBBBBBBBBBBBBBBBbbkMMkMMMMMMMMMMMMMMMkggggggggggkMMMMMMMMMMMMMMMkMMkbbBBBBBBBBBBBBBBBBBBBBbbkMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkkkkkkkkkkkkmMkGgMMkbbBBBBBBBBBBBBbbbbbbbbbbkMMkMMMMMkkkkkkkkkkkggGGGGGGggkkkkkkkkkkkMMMMMkMMkbbBBBBBBBBBBBBbbbbbbbbbbkMMgGklmkkkkkkkkkkkkmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMkbbbbbbbbbbbbbbbbbbbbbbbbkMMkMMMMMMMMMMMMMMMkggggggggggkMMMMMMMMMMMMMMMkMMkbbbbbbbbbbbbbbbbbbbbbbbbkMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkxkkgklmkkkkkkkkkkkkmMkGgMMkkkkkkkkkkkkkkkkkkkkkkkkkkMMkMMMMMkkkkkkkkkkkggggggggggkkkkkkkkkkkMMMMMkMMkkkkkkkkkkkkkkkkkkkkkkkkkkMMgGklmkkkkkkkkkkkkmMkgkkxkkmkk.',
    '.kkmkkxkkgklmmmmmmmmmmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMkkkkkkkkkkkkMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmmmmmmmmmmMkgkkxkkmkk.',
    '.kkmkkhkkgklmmmmmmmmmmmmmmMkGgMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMgGklmmmmmmmmmmmmmmMkgkkhkkmkk.',
    '.kkmkkxkkgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgkkxkkmkk.',
    '.kkmkkxkkgkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkmmmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmmmkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkmmmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmmmkk.kkgkkxkkmkk.',
    'khhhhhhhhhhk.kkmmmmmammmmmmmmmmmommmmmmmmmmmommmmmmmmmmmfmmmmmmmmmmmammmmmmmmmmmommmmmmmmmmmommmmmmmmmmmfmmmmmmmmmmmammmmmmmmmmmommmmmmmmmmmommmmmmmmkk.khhhhhhhhhhk',
    'kggggggggggk.kkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkk.kggggggggggk',
    'kkkkkkkkkkkkkkkmmmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmbbmBBmbbmbbmbbmmmkkkkkkkkkkkkkkk',
    'kkkmkkxkkgkk.kkmmmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmbBmBBmbBmbBmbBmmmkk.kkgkkxkkmkkk',
    '.kkmkkxkkgkk.kkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMMlMMMMMMMMkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.kkgkkxkkmkk.',
    '.kkmkkxkkgkk.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.kkgkkxkkmkk.',
    '.kkMkkxkkGkk..kkeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeekk..kkGkkxkkMkk.',
    '..kkkkkkkkk.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....kkkkkkkkk..',
    '....................................................................................................................................................................',
  ],
  WINDOW: [
    '......kuuuuuuuuuuuuuuuuuuk......',
    '.....kuuuuuuuuuuuuuuuuuuuuk.....',
    '.....kuuuuuuuuukkuuuuuuuuuk.....',
    '....kuuuuuuuukxxxxkuuuuuuuuk....',
    '....kuuuuuuukxxxkxxkuuuuuuuk....',
    '...kuuuuuuukxkggggkxkuuuuuuuk...',
    '...kuuuuuuuxxggggggxxuuuuuuuk...',
    '...kuuuuuukxxggggggxxkuuuuuuk...',
    '..kuuuuuuukxkggggggxkkuuuuuuuk..',
    '..kuuuuuuuuxxggggggxxuuuuuuuuk..',
    '..kuuuuuuuukxkggggkxkuuuuuuuuk..',
    '..kuuuuuuuuukxxxxxxkuuuuuuuuuk..',
    '..kuuuuuuuuuukxxkxkuuuuuuuuuuk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kuuuuuuuukuuuuuuuukuuuuuuuuk..',
    '..kuuxxxxuukuuxxxxuukuuxxxxuuk..',
    '..kuuxggxuukuuxggxuukuuxggxuuk..',
    '..kuuxggxuukuuxggxuukuuxggxuuk..',
    '..kuuxggxuukuuxxxxuukuuxggxuuk..',
    '..kuuxxxxuukuuxxxxuukuuxxxxuuk..',
    '..kuuuuuuuukuuxxxxuukuuuuuuuuk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kuuuuuuuukuuuuuuuukuuuuuuuuk..',
    '..kvvvvvvvvkvvvvvvvvkvvvvvvvvk..',
    '..kvvvvvvvvkvvvvvvvvkvvvvvvvvk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kvvvvvvvvkvvvvvvvvkvvvvvvvvk..',
    '..kvvvvvvvvkvvvvvvvvkvvvvvvvvk..',
    '..kuuuuuuuukuuuuuuuukuuuuuuuuk..',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    '.kmmmmmmmmmmmmmmmmmmmmmmmmmmmmk.',
    '.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
  ],
  BANNER: [
    '.kkkkkkkkkkkkkkkkkkkkkk.',
    'khhhhhhhhhhhhhhhhhhhhhhk',
    'kGGGGGGGGGGGGGGGGGGGGGGk',
    'kkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkddddddddddddddddddkk.',
    '.kkxxxxrxxxxxxxrxxxrrkk.',
    '.kkxxxxrxkkkkkkrxxxrrkk.',
    '.kkxxxxrkbbbbbbkxxxrrkk.',
    '.kkxxxxkbbbbbbbbkxxrrkk.',
    '.kkxxxkbkkbbbbkkbkxrrkk.',
    '.kkxxxkbkkbbbbkkbkxrrkk.',
    '.kkxxxkbbbbkkbbbBkxrrkk.',
    '.kkxxxxkbbbbbbbBkxxrrkk.',
    '.kkxxxxrkbkbkbBkxxxrrkk.',
    '.kkxxxxrxkkkkkkrxxxrrkk.',
    '.kkxxxxrxxxxxxxrxxxrrkk.',
    '.kkxxxxrxxxxxxxrxxxrrkk.',
    '.kkxxxxrxxxxxxxrxxxrrkk.',
    '.kkggggggggggggggggggkk.',
    '.kkxxxxrxxxkkxxrxxxrrkk.',
    '.kkxxxxrxxkkkkxrxxxrrkk.',
    '.kkxxxxrxkk..kkrxxxrrkk.',
    '.kkxxxxrkk....kkxxxrrkk.',
    '.kkxxxxkk......kkxxrrkk.',
    '.kkxxxkk........kkxrrkk.',
    '.kkxxkk..........kkrrkk.',
    '.kkxkk............kkrkk.',
    '.kkkk..............kkkk.',
    '..kk................kk..',
    '........................',
  ],
  CRATE: [
    '.kkkkkk..kkkkkk..kkkkkk.....',
    '.kPPPPk..kppppk..kPPPPk.....',
    '.kPBBPk..kpBBpk..kPBBPk.....',
    '.kPPPPk..kppppk..kPPPPk.....',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLWk',
    'kLgwwwwwwwwwwwwwwwwwwwwwwgWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kLwwLWwwwwwwwwwwwwwwwwwLWwWk',
    'kLwwwwLWwwwwwwwwwwwwwLWwwwWk',
    'kLwwwwwwLWwwwwwwwwwLWwwwwwWk',
    'kLwwwwwwwwLWwwwwwLWwwwwwwwWk',
    'kLwwwwwwwwwwLWwLWwwwwwwwwwWk',
    'kLwwwwwwwwwwwLWWwwwwwwwwwwWk',
    'kLwwwwwwwwwLWwwwLWwwwwwwwwWk',
    'kLwwwwwwwLWwwwwwwwLWwwwwwwWk',
    'kLwwwwwLWwwwwwwwwwwwLWwwwwWk',
    'kLwwwLWwwwwwwwwwwwwwwwLWwwWk',
    'kLwLWwwwwwwwwwwwwwwwwwwwLWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLgwwwwwwwwwwwwwwwwwwwwwwgWk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  PAPER_STACK: [
    '.kkkkkkkkkkkkkk.',
    'kpppppppppppppPk',
    'kPPPPPPPPPPPPPPk',
    'kpppppppppppppPk',
    'kPPPPPPPPPPPPPPk',
    'kpppppppppppppPk',
    'kPPPPPPPPPPPPPPk',
    'kpppppppppppppPk',
    'kkkkkkkkkkkkkkkk',
    '..kpppppppppppPk',
    '..kPPPPPPPPPPPPk',
    '..kpppppppppppPk',
    '..kPPPPPPPPPPPPk',
    '..kpppppppppppPk',
    'kkkkkkkkkkkkkkkk',
    'kppppppxrpppppPk',
    'kPPPPPPxrPPPPPPk',
    'kppppppxrpppppPk',
    'kPPPPPPxrPPPPPPk',
    'kppppppxrpppppPk',
    'kPPPPPPxrPPPPPPk',
    'kppppppxrpppppPk',
    'kPPPPPPxrPPPPPPk',
    'kkkkkkkkkkkkkkkk',
  ],
  SCROLL_PILE: [
    '........kkkkkkkk...kkkkkkkk.........',
    '........kpPppppk...kppxxppk.........',
    '........kppBpppk...kppxxppk.........',
    '......kkkkkkkkkk.kkkkkkkkkk.........',
    '......kPbkppkPbk.kPbkppkPbk.........',
    '......kbBkPPkbBk.kbBkPPkbBk.........',
    '......kkkkkkkkkk.kkkkkkkkkk.........',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...',
    '..kPbkppppppppkPbkPbkpppxxpppkPbk...',
    '..kbBkPPPPPPPPkbBkbBkPPPxxPPPkbBk...',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    '.kPbkppppppppppppppppppppppppppkPbk.',
    '.kbBkPPPPPPPPPPPPPPPPPPPPPPPPPPkbBk.',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
  ],
  BOOKS: [
    '..kkkkkkkkkkkkkk....',
    '..kxxgxxxxxxxxxk....',
    '..kxppppppppppPk....',
    '..krrgrrrrrrrrrk....',
    'kkkkkkkkkkkkkkkkkk..',
    'kuuguuuuuuuuuuuuuk..',
    'kuppppppppppppppPk..',
    'knngnnnnnnnnnnnnnk..',
    'kkkkkkkkkkkkkkkkkk..',
    '..kvvgvvvvvvvvvvvk..',
    '..kvppppppppppppPk..',
    '..knngnnnnnnnnnnnk..',
    'kkkkkkkkkkkkkkkkkkkk',
    'kWWgWWWWWWWWWWWWWWWk',
    'kWppppppppppppppppPk',
    'kWWWWWWWWWWWWWWWWWWk',
    'knnnnnnnnnnnnnnnnnnk',
    'kkkkkkkkkkkkkkkkkkkk',
  ],
  LOOSE_A: up(['kkkkk', 'kpppk', 'kpPpk', 'kkkkk']),
  LOOSE_B: up(['kkkk', 'kPpk', 'kppk', 'kpPk', 'kkkk']),
  GAUGE: [
    '...kkkkkk...',
    '..khhhhhgk..',
    '.khhbbbxxgk.',
    'khhBbbbbkggk',
    'khbbbbbkbxGk',
    'khbbbbkbbbGk',
    'khBbbMbbbBGk',
    'khbbbbBbbbGk',
    'kggbbbbbbGGk',
    '.kggbbbbGGk.',
    '..kgGGGGGk..',
    '...kkkkkk...',
  ],
  CENSER: [
    '....kk....',
    '....lM....',
    '....mM....',
    '....kk....',
    '....lM....',
    '....mM....',
    '....kk....',
    '...kkkk...',
    '..khggGk..',
    '.khggggGk.',
    'khgkffkgGk',
    'kgkfFFfkGk',
    'kgkfFFfkGk',
    'khgkffkgGk',
    '.kgggggGk.',
    '..kgggGk..',
    '...kGGk...',
    '....kk....',
    '..........',
    '..........',
  ],
  // Grand exit gate (32x30 logical): brass pointed arch, skull keystone, pinnacled piers, step; the opening
  // (16x22 at +8,+5) is transparent and shows the two iron leaves, which carry the split Cog Mechanicus.
  GATE: [
    '......kk................................................kk......',
    '......kk................................................kk......',
    '......kk....................kkkkkkkk....................kk......',
    '.....khGk..................kbbbbbbbbk..................khGk.....',
    '.....khGk.................kbbbbbbbbbBk.................khGk.....',
    '....khhGGk...............kbbbbbbbbbbbBk...............khhGGk....',
    '....khhGGk.............khkbbkkkbbkkkbBkhk.............khhGGk....',
    '...khhhGGGk...........khgkbkkkkbbkaakBkGgk...........khhhGGGk...',
    '...khhhGGGk............kGkbkkkkbbkaakBkGk............khhhGGGk...',
    '..khhhhGGGGk..........khgkbbkkbbbbkkbBkghk..........khhhhGGGGk..',
    '.kkkkkkkkkkkk........khgggkbbbbkkbbbBkggghk........kkkkkkkkkkkk.',
    '.khhhhhhhhhhk......kkhgFggkkBbbbbbbBkkggFghkk......khhhhhhhhhhk.',
    '.kggggggggggk......khgggGk.kbkbkbkbBk.kGggghk......kggggggggggk.',
    '.kGGGGGGGGGGkkkkk.khgggGk..kBkBkBkBBk..kGggghk.kkkkkGGGGGGGGGGk.',
    '..klmmggmmMkgggggkhgggGk....kkkkkkkk....kGggghkgggggklmmggmmMk..',
    '..klmmggmmMkGGGGGhgggGk..................kGggghGGGGGklmmggmmMk..',
    '..klmmggmmMkMMMkkgggGk....................kGgggkkMMMklmmggmmMk..',
    '..klmmggmmMkMMMkhgggk......................kggghkMMMklmmggmmMk..',
    '..klmmggmmMkMMkhgFgk........................kgFghkMMklmmggmmMk..',
    '..kllmhhmlMkMMkhggGk........................kGgghkMmkllmhhmlMk..',
    '..klmmggmmMkMkhgggk..........................kggghkMklmmggmmMk..',
    '..klmmggmmMkMkhggk............................kgghkMklmmggmmMk..',
    '..klmmggmmMkMkgggk............................kgggkMklmmggmmMk..',
    '..klmmggmmMkkhggGk............................kGgghkklmmggmmMk..',
    '..klmmggmmMkkhggk..............................kgghkklmmggmmMk..',
    '..kllmggmlMkkgggk..............................kgggkkllmggmlMk..',
    '..klmmggmmMkkgggk..............................kgggkklmmggmmMk..',
    '..klmmhhmmMkhggk................................kgghklmmhhmmMk..',
    '..klmmggmmMkhgFk................................kFghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..kllmggmlMkhggk................................kgghkllmggmlMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmhhmmMkhggk................................kgghklmmhhmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..kllmggmlMkhggk................................kgghkllmggmlMk..',
    '..klmmggmmMkFhgk................................kgFhklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..kllmhhmlMkhggk................................kgghkllmhhmlMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkFhgk................................kgFhklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..klmmggmmMkhggk................................kgghklmmggmmMk..',
    '..kllmggmlMkhggk................................kgghkllmggmlMk..',
    '.kkkkkkkkkkkkggk................................kggkkkkkkkkkkkk.',
    '.kllllllllllkggk................................kggkllllllllllk.',
    '.kmmmmmmmmmmkggk................................kggkmmmmmmmmmmk.',
    '.kmmmmmmmmmmkggk................................kggkmmmmmmmmmmk.',
    '......kllllllllllllllllllllllllllllllllllllllllllllllllllk......',
    '......kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk......',
    '......kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk......',
    'kllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllk',
    'kmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  GATE_L: [
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMllllllllllllMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkkk',
    'kMlmmmmmmmmmmkMh',
    'kMlmmmmmmkmmmkkh',
    'kMlkkkkkkhhkkhhh',
    'kMMMMMMMkhhhhhhg',
    'kMMMMMMMMhhhhkkk',
    'khFhhhFhhkhhkkkk',
    'kGGGGGGGkhhkkbbb',
    'kkkkkkkkkhkkbbbb',
    'kMMMMMhhhhkkbkkb',
    'kMMMMMhhhgkkbkkb',
    'kMMMMMhhggkkbbbb',
    'kMMMMMMMkgkMkbkb',
    'khFhhhFhkggkkBkB',
    'kGGGGGGGGkggkkkk',
    'kkkkkkkkkggggkkk',
    'kMMMMMMMkggggggg',
    'kMMMMMMMkggkkggg',
    'kMlllllllklllkkG',
    'kMlmmmmmmmmmmkMG',
    'kMlmmmmmmmmmmkkk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlkkkkkkkkkkkMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
  ],
  GATE_R: [
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMllllllllllllMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kklmmmmmmmmmmkMk',
    'hMlmmmmmmmmmmkMk',
    'hkkmmmkmmmmmmkMk',
    'gggkkggkkkkkkkMk',
    'gggggggkMMMMMMMk',
    'kkkggggMMMMMMMMk',
    'kkkkggkhhhFhhhFk',
    'mmmkkggkGGGGGGGk',
    'mllmkkgkkkkkkkkk',
    'mkakkkggGGMMMMMk',
    'mkakkkgGGGMMMMMk',
    'mmmMkkGGGGMMMMMk',
    'mlmkMkGkMMMMMMMk',
    'mMmkkGGkhhFhhhFk',
    'kkkkGGkGGGGGGGGk',
    'kkkGGGGkkkkkkkkk',
    'gGGGGGGkMMMMMMMk',
    'GGGkkGGkMMMMMMMk',
    'GkklllklllllllMk',
    'GMlmmmmmmmmmmkMk',
    'kklmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlmmmmmmmmmmkMk',
    'kMlkkkkkkkkkkkMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
    'kMMMMMMMMMMMMMMk',
  ],
  // Refectorium: a plank table with recaff mugs and ration crumbs (46x8), and its bench (46x4).
  TABLE: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLk',
    'kwwwwwwwwWwwwwwwwwwwwwwwwwwwwwwwWwwwwwwwwwwwwwwwwwwwwwwWwwwwwwwwwwwwwwwwwwwwwwWwwwwwwwwwwwwk',
    'kwWwwwwwwwwwwwwkkkkwwwwwwWwwwwwwwwwwwwwwwwwkkkkwWwwwwwwwwwwwwwwwwwwwwwwkkkkwwwwwwwwwwkkkkkwk',
    'kwwwwwwwwwwwwwkhnngkwwwwwwwkkkkkwwwwwwwwwWkhnngkwwwwwwwwwwwwwwwwWwwwwwkhnngkwwwwwwwwkbbbbkwk',
    'kWWWWWWWWWWWWWkgnnGkkWWWWWkbbbbBkWWWWWWWWWkgnnGkkWWWWWWWkkWWWWWWWWWWWWkgnnGkkWWWWWWWkbPpbkWk',
    'kLLLLLLLLLLLLLkhggGkgLLLLLkbPpbBkLLLLLLLLLkhggGkgLLLLLLLPkLLLLLLLLLLLLkhggGkgLLLLLLLLkkkkkLk',
    'kwwwwwwwwwwwwwkgggGkkwwwwwwkkkkkwwwwwwwwwwkgggGkkwwwwwwwwwwwwwwwwwWwwwkgggGkkwwwwwwwwwwwwWwk',
    'kwwwwwwwwwwwwWwkkkkwwwwwwwwwwwwwwwwwWwwwwwwkkkkwwwwwwwwwwwwWwwwwwwwwwwwkkkkwwwwwwwWwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kkkkwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkk',
    'kkkkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  BENCH: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kWWWW.......................................WWWW.......................................WWWWk',
    'kWWWW.......................................WWWW.......................................WWWWk',
    'kkkkk.......................................kkkk.......................................kkkkk',
  ],
};
